### ISSUE TITLE
Category Landing [Tablet]: (From QA) Overlapping photo

### ISSUE THREAD

**Issue by MartyBeckers** [nickpaventi/culligan-diy#138] opened 2015-04-11 01:01 UTC
http://dev.culligandiy.com/Whole-House-Systems: Product box is overlapping View details button on an iPad Air in vertical orientation:

![image](https://cloud.githubusercontent.com/assets/11283011/7099603/87a71428-dfab-11e4-9a11-2875c9a58f89.png)

**Comment by yuchentai** [comment] 2015-04-13 15:47
@MartyBeckers this problem might be caused by extra closing div tag in Line 31 category-landing/index.html.  Please check the html code on dev. Thanks

<div class="three-forth-hero">
	<img src="../img/innovative-droplet-full/water-bg.png" class="water-bg" />
		{% include three-forth-hero.html %}
	</div>  <----------------------- This needs to be removed.
</div>

**Comment by MartyBeckers** [comment] 2015-04-13 16:08
@yuchentai can you take another look at the source for http://dev.culligandiy.com/Whole-House-Systems?  When I check lines 574-602 (the subcategory headline and featured product), I'm counting 10 open div tags and 10 closing div tags.  If you still think there's an extra, can you paste in a larger selection of the code and point to the problem again?

**Comment by yuchentai** [comment] 2015-04-13 16:22
@MartyBeckers It's hard to locate the problem when checking the rendered html in browser.  I found the extra closing div tag in source file.  Once I removed that closing tag.  The page render correctly on my local.

File Path: /_build/category_landing/index.html
Code:
---
layout: default
title: Category Landing
slug: category-landing
path: ../
---

{% include tall-hero.html %}

&lt;div class="navigation-subcategory"&gt;
	  {% include navigation-subcategory.html %}
&lt;/div&gt;

&lt;div class="row"&gt;
	&lt;div class="small-12 medium-8 columns"&gt;
		{% include page-content.html %}
	&lt;/div&gt;
&lt;/div&gt;

&lt;div class="row collapse"&gt;
	&lt;div class="columns"&gt;
		&lt;h2 class="subcategory-headline"&gt;
			Sub category one headline.
		&lt;/h2&gt;
	&lt;/div&gt;
&lt;/div&gt;

&lt;div class="three-forth-hero"&gt;
	&lt;img src="../img/innovative-droplet-full/water-bg.png" class="water-bg" /&gt;
		{% include three-forth-hero.html %}
	&lt;/div&gt;  &lt;------------------------
&lt;/div&gt;

&lt;div class="four-container"&gt;
	{% include four-featured-products.html %}
&lt;/div&gt;

&lt;div class="row collapse"&gt;
	&lt;div class="columns"&gt;
		&lt;h2 class="subcategory-headline top-spacing"&gt;
			Sub category one headline.
		&lt;/h2&gt;
	&lt;/div&gt;
&lt;/div&gt;

&lt;div class="one-forth-hero"&gt;
	{% include one-forth-hero.html %}
&lt;/div&gt;

{% include two-featured-products.html %}

**Comment by MartyBeckers** [comment] 2015-04-13 17:46
Ahh yes I actually remember that extra closing div tag because it was breaking features in Kentico when we first integrated the HTML.  I believe that has already been removed, but if you're still seeing an extra close div tag somewhere in the rendered page source, please point me to it.

**Comment by nickpaventi** [comment] 2015-04-13 18:27
This has been fixed.

**Closed by nickpaventi** 2015-04-13 18:27 UTC
Labels: High Priority
